id = "smalisp"
name = "Smalisp"
version = "0.1.0"
schema_version = 1
authors = ["Abhi <abhi@revengi.in>"]
description = "Smali language support for zed"
repository = "https://github.com/AbhiTheModder/smalisp.git"

[grammars.smali]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-smali"
rev = "fdfa6a1febc43c7467aa7e937b87b607956f2346"

[language_servers.smalisp]
name = "Smali Language Server"
languages = ["Smali"]
